"""added columns

Revision ID: 916c6fc4b22f
Revises: 35d670302a15
Create Date: 2023-06-06 14:11:02.207122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916c6fc4b22f'
down_revision = '35d670302a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
